# will be merged with mkdocs-defaults.yml

# Project information
site_name: MkDocs Docmark
site_description: Enhanced theme for MkDocs
site_author: Joshua Burnett
site_url: http://yakworks.github.io/docmark/

# Repository
repo_name: yakworks/docmark
repo_url: https://github.com/yakworks/docmark
edit_uri: edit/docmark/docs/

# Copyright
copyright: 'Copyright &copy; 2020 Joshua Burnett'

# Theme directory
theme_dir: material
# use installed theme
# theme: 'docmark' # Use this one if not developing here

# Options
extra:
  # can possibly use this for doing this from environmental variables
  # https://github.com/cmacmackin/md-environ
  version: 1.10.13
  # logo: images/logo_white.png
  #
  # use console.log(btoa('some-password')) in chrome console to generate.
  # If this is set js will force a div overlay over all the page content.
  # this is NOT security. A user can always just use the debubg console and remove the overlay div or just look at the html source for the page
  # password: 'c2VjcmV0' # <- resolves to 'secret'
  #
  # adds <meta name="robots" content="noindex,nofollow"> to keep search engines from indexing this
  # noindex: true
  #
  # font:
  #   text: 'Open Sans'
  #   code: 'Ubuntu Mono'
  # feature:
  # tabs: true
  # palette:
  #   primary: 'orange' #'blue grey'
  #   accent: indigo
    
# Google Analytics
# google_analytics:
#  - UA-4372852-1 #!!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
#  - auto # this is not used here as we switched to googles new gtag.js

# Extensions
# markdown_extensions: # see deploy/mkdocs-defaults.yml
